kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hello
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always


---

kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 3000
  selector:
    app: hello

